name: Update Rankings

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-rankings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests  # Include any other dependencies your script needs

    - name: Run script
      run: |
        python fetch-my-rank.py  # Adjust the path if your script is in a subdirectory

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add README.md  # Add the file that is updated by your script
        git commit -m "Update rankings"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
